package io.heyram.anomaly

import java.sql.Timestamp



case class Transaction(id:String,
                       duration:Double,
                       protocol_type:String,
                       service:String,
                       flag:String,
                       src_bytes:Double,
                       dst_bytes:Double,
                       land:Double,
                       wrong_fragment:Double,
                       urgent:Double,
                       hot:Double,
                       num_failed_logins:Double,
                       logged_in:Double,
                       num_compromised:Double,
                       root_shell:Double,
                       su_attempted:Double,
                       num_root:Double,
                       num_file_creations:Double,
                       num_shells:Double,
                       num_access_files:Double,
                       num_outbound_cmds:Double,
                       is_host_login:Double,
                       is_guest_login:Double,
                       count:Double,
                       srv_count:Double,
                       serror_rate:Double,
                       srv_serror_rate:Double,
                       rerror_rate:Double,
                       srv_rerror_rate:Double,
                       same_srv_rate:Double,
                       diff_srv_rate:Double,
                       srv_diff_host_rate:Double,
                       dst_host_count:Double,
                       dst_host_srv_count:Double,
                       dst_host_same_srv_rate:Double,
                       dst_host_diff_srv_rate:Double,
                       dst_host_same_src_port_rate:Double,
                       dst_host_srv_diff_host_rate:Double,
                       dst_host_serror_rate:Double,
                       dst_host_srv_serror_rate:Double,
                       dst_host_rerror_rate:Double,
                       dst_host_srv_rerror_rate:Double
                       )

case class DstreamTransaction(id:String,
                              duration:Double,
                              protocol_type:String,
                              service:String,
                              flag:String,
                              src_bytes:Double,
                              dst_bytes:Double,
                              land:Double,
                              wrong_fragment:Double,
                              urgent:Double,
                              hot:Double,
                              num_failed_logins:Double,
                              logged_in:Double,
                              num_compromised:Double,
                              root_shell:Double,
                              su_attempted:Double,
                              num_root:Double,
                              num_file_creations:Double,
                              num_shells:Double,
                              num_access_files:Double,
                              num_outbound_cmds:Double,
                              is_host_login:Double,
                              is_guest_login:Double,
                              count:Double,
                              srv_count:Double,
                              serror_rate:Double,
                              srv_serror_rate:Double,
                              rerror_rate:Double,
                              srv_rerror_rate:Double,
                              same_srv_rate:Double,
                              diff_srv_rate:Double,
                              srv_diff_host_rate:Double,
                              dst_host_count:Double,
                              dst_host_srv_count:Double,
                              dst_host_same_srv_rate:Double,
                              dst_host_diff_srv_rate:Double,
                              dst_host_same_src_port_rate:Double,
                              dst_host_srv_diff_host_rate:Double,
                              dst_host_serror_rate:Double,
                              dst_host_srv_serror_rate:Double,
                              dst_host_rerror_rate:Double,
                              dst_host_srv_rerror_rate:Double
                              )


/* Spark Dataset case class for mapping messages received from Kafka in Structured Streaming*/
case class TransactionKafka(topic: String, partition: Int, offset: Long, timestamp: Timestamp, timestampType:Int, transaction:Transaction)


